name: Quality Check

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

permissions:
  contents: read

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      # To automatically get bug fixes and new PHP versions for shivammathur/setup-php,
      # change this to (see https://github.com/shivammathur/setup-php#bookmark-versioning):
      - uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
        with:
          php-version: '8.2'  # Change si ton projet utilise une autre version

      - uses: actions/checkout@v4

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: |
          composer update --lock
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
        working-directory: application

      - name: Check vendor/bin contents
        run: ls -la vendor/bin
        working-directory: application

      - name: Ensure PHP_CodeSniffer is installed
        run: composer require --dev squizlabs/php_codesniffer
        working-directory: application

      - name: Run PHP_CodeSniffer
        run: vendor/bin/phpcs --standard=PSR2 src/
        working-directory: application

      - name: Ensure PHPStan is installed
        run: composer require --dev phpstan/phpstan
        working-directory: application

      - name: Run PHPStan
        run: vendor/bin/phpstan analyze src/
        working-directory: application

      - name: Ensure PHPMD is installed
        run: composer require --dev phpmd/phpmd
        working-directory: application

      - name: Run PHPMD
        run: vendor/bin/phpmd src/ text cleancode,codesize,controversial,design
        working-directory: application

      - name: Create Database
        run: |
          mkdir -p data
          touch data/database.sqlite
        working-directory: application